ProyectoGym/Models/Usuario.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ProyectoGym.Models
{
    public class Usuario
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int Id { get; set; }
        [Required(ErrorMessage = "Debe especificar un nombre")]
        public string Nombres { get; set; }
        [Required(ErrorMessage = "Debe especificar un apellido")]
        public string Apellidos { get; set; }
        [Required(ErrorMessage = "Debe especificar un nombre de usuario")]
        [Display(Name = "Nombre de usuario")]
        public string NombreUsuario { get; set; }
        [Required(ErrorMessage = "Debe especificar una contraseña")]
        [DataType(DataType.Password)]
        public string Password { get; set; }
        [Required(ErrorMessage = "Debe especificar un tipo de perfil")]
        [EnumDataType(typeof(Perfil))]
        public Perfil Perfil { get; set; }

        [EnumDataType(typeof(Plan))]
        public Plan? Plan { get; set; }

        public List<Rutina>? rutinas { get; set; }
    }
}

ProyectoGym/Controllers/ActividadesUsuariosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ProyectoGym.Context;
using ProyectoGym.Models;

namespace ProyectoGym.Controllers
{
    public class ActividadesUsuariosController : Controller
    {
        private readonly ProyectoGymContext _context;

        public ActividadesUsuariosController(ProyectoGymContext context)
        {
            _context = context;
        }

        // GET: ActividadesUsuarios
        public async Task<IActionResult> Index(int id)
        {
            ViewBag.User = await _context.Usuarios.FirstOrDefaultAsync(m => m.Id == id);


            var datos = (from au in _context.ActividadesUsuario
                         join u in _context.Usuarios on au.Usuario.Id equals u.Id
                         join a in _context.Actividades on au.Actividad.Id equals a.Id
                         where u.Id == id
                         select new ActividadesUsuario {
                            Id = au.Id,
                            Usuario = u,
                            Actividad = a
                         }).ToListAsync();

            return View(await datos);
        }

        // GET: ActividadesUsuarios/Create
        public ActionResult Create(int userId)
        {
            ViewBag.User = _context.Usuarios.FirstOrDefault(m => m.Id == userId);


            var actividadesDelUsuario = from au in _context.ActividadesUsuario 
                                        where au.Usuario.Id == userId
                                        select au.Actividad.Id;

            var ActividadesParaAgregar = from a in _context.Actividades
                                         where !actividadesDelUsuario.Contains(a.Id)
                                         select a;

            ViewData["ActividadesParaAgregar"] = ActividadesParaAgregar.ToList();
            return View();
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(int userId, int actividadId)
        {
            ActividadesUsuario actividadesUsuario = new ActividadesUsuario();
            if (ModelState.IsValid)
            {
                actividadesUsuario.Actividad = await _context.Actividades.FindAsync(actividadId);
                actividadesUsuario.Usuario = await _context.Usuarios.FindAsync(userId);
                _context.Add(actividadesUsuario);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index), new { @id = userId });
            }
            return View(actividadesUsuario);
        }

        // GET: ActividadesUsuarios/Delete/5
        public async Task<IActionResult> Delete(int? id, int? userId)
        {
            if (id == null)
            {
                return NotFound();
            }


            //var actividadesUsuario = await _context.ActividadesUsuario
            //    .FirstOrDefaultAsync(m => m.Id == id);

            var actividadesUsuario = await (from au in _context.ActividadesUsuario
                                            join a in _context.Actividades on au.Actividad.Id equals a.Id
                                            where au.Id == id
                                            select new ActividadesUsuario {
                                                Id = au.Id,
                                                Actividad = a
                                            }).FirstOrDefaultAsync();


            if (actividadesUsuario == null)
            {
                return NotFound();
            }

            ViewBag.userId = userId;
            return View(actividadesUsuario);
        }

        // POST: ActividadesUsuarios/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id, int? userId)
        {
            var actividadesUsuario = await _context.ActividadesUsuario.FindAsync(id);
            _context.ActividadesUsuario.Remove(actividadesUsuario);
            await _context.SaveChangesAsync();


            return RedirectToAction(nameof(Index), new { @id = userId });
        }

        private bool ActividadesUsuarioExists(int id)
        {
            return _context.ActividadesUsuario.Any(e => e.Id == id);
        }
    }
}

ProyectoGym/Controllers/RutinaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ProyectoGym.Context;
using ProyectoGym.Models;

namespace ProyectoGym.Controllers
{
    public class RutinaController : Controller
    {
        private readonly ProyectoGymContext _context;

        public RutinaController(ProyectoGymContext context)
        {
            _context = context;
        }

        // GET: Rutina
        public async Task<IActionResult> Index(int userId)
        {
            ViewBag.User = await _context.Usuarios.FirstOrDefaultAsync(m => m.Id == userId);
            return View(await _context.Rutinas.Where(rutina => rutina.UsuarioId == userId).OrderByDescending(rutina => rutina.RutinaId).ToListAsync());
        }

        // GET: Rutina/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var rutina = await _context.Rutinas
                .FirstOrDefaultAsync(m => m.RutinaId == id);
            if (rutina == null)
            {
                return NotFound();
            }

            return View(rutina);
        }

        // GET: Rutina/Create
        public IActionResult Create(int userId)
        {
            ViewBag.UserId = userId;
            return View();
        }

        // POST: Rutina/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("RutinaId,FechaInicio,FechaFin,Detalle, UsuarioId")] Rutina rutina)
        {
            if (ModelState.IsValid)
            {
                var rutinas = (from r in _context.Rutinas
                               where r.UsuarioId == rutina.UsuarioId && r.FechaFin == null
                               select r
                               ).ToArray();

                foreach (var unaRutina in rutinas) {
                    unaRutina.FechaFin = rutina.FechaInicio;
                    _context.Update(unaRutina);
                }

                _context.Add(rutina);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index), new { @userId = rutina.UsuarioId });
            }
            return View(rutina);
        }

        // GET: Rutina/Edit/5
        public async Task<IActionResult> Edit(int? id, int userId)
        {
            ViewBag.UserId = userId;

            if (id == null)
            {
                return NotFound();
            }

            var rutina = await _context.Rutinas.FindAsync(id);
            if (rutina == null)
            {
                return NotFound();
            }
            return View(rutina);
        }

        // POST: Rutina/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("RutinaId,FechaInicio,FechaFin,Detalle,UsuarioId")] Rutina rutina)
        {
            if (id != rutina.RutinaId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(rutina);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!RutinaExists(rutina.RutinaId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index), new { @userId=rutina.UsuarioId });
            }
            return View(rutina);
        }

        // GET: Rutina/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var rutina = await _context.Rutinas
                .FirstOrDefaultAsync(m => m.RutinaId == id);
            if (rutina == null)
            {
                return NotFound();
            }

            return View(rutina);
        }

        // POST: Rutina/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var rutina = await _context.Rutinas.FindAsync(id);
            _context.Rutinas.Remove(rutina);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index), new { @userId = rutina.UsuarioId});
        }

        private bool RutinaExists(int id)
        {
            return _context.Rutinas.Any(e => e.RutinaId == id);
        }
    }
}

ProyectoGym/Controllers/UsuarioController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ProyectoGym.Context;
using ProyectoGym.Models;

namespace ProyectoGym.Controllers
{
    public class UsuarioController : Controller
    {
        private readonly ProyectoGymContext _context;

        public UsuarioController(ProyectoGymContext context)
        {
            _context = context;
        }

        // GET: Usuario
        public async Task<IActionResult> Index()
        {
            return View(await _context.Usuarios.ToListAsync());
        }

        // GET: Usuario/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var usuario = await _context.Usuarios
                .FirstOrDefaultAsync(m => m.Id == id);
            if (usuario == null)
            {
                return NotFound();
            }

            return View(usuario);
        }

        // GET: Usuario/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Usuario/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Nombres,Apellidos,NombreUsuario,Password,Perfil,Plan")] Usuario usuario)
        {
            if (ModelState.IsValid)
            {
                _context.Add(usuario);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(usuario);
        }

        // GET: Usuario/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var usuario = await _context.Usuarios.FindAsync(id);
            if (usuario == null)
            {
                return NotFound();
            }
            return View(usuario);
        }

        // POST: Usuario/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Nombres,Apellidos,NombreUsuario,Password,Perfil,Plan")] Usuario usuario)
        {
            if (id != usuario.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(usuario);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!UsuarioExists(usuario.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(usuario);
        }

        // GET: Usuario/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var usuario = await _context.Usuarios
                .FirstOrDefaultAsync(m => m.Id == id);
            if (usuario == null)
            {
                return NotFound();
            }

            return View(usuario);
        }

        // POST: Usuario/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var actividades = (from au in _context.ActividadesUsuario
                               where au.Usuario.Id == id
                               select au
                               ).ToArray();

            foreach (var actividad in actividades) { 
                _context.ActividadesUsuario.Remove(actividad);
            }

            var rutinas = (from r in _context.Rutinas
                               where r.UsuarioId == id
                               select r
                               ).ToArray();

            foreach (var rutina in rutinas)
            {
                _context.Rutinas.Remove(rutina);
            }

            var usuario = await _context.Usuarios.FindAsync(id);
            _context.Usuarios.Remove(usuario);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool UsuarioExists(int id)
        {
            return _context.Usuarios.Any(e => e.Id == id);
        }
    }
}

ProyectoGym/Views/Usuario/Create.cshtml
@model ProyectoGym.Models.Usuario

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Crear</h1>

<h4>Usuario</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Nombres" class="control-label"></label>
                <input asp-for="Nombres" class="form-control" />
                <span asp-validation-for="Nombres" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Apellidos" class="control-label"></label>
                <input asp-for="Apellidos" class="form-control" />
                <span asp-validation-for="Apellidos" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="NombreUsuario" class="control-label"></label>
                <input asp-for="NombreUsuario" class="form-control" />
                <span asp-validation-for="NombreUsuario" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Password" class="control-label"></label>
                <input asp-for="Password" class="form-control" />
                <span asp-validation-for="Password" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Perfil" class="control-label"></label>
                <select asp-for="Perfil" class="form-control" asp-items="Html.GetEnumSelectList<Perfil>()" onchange="listenerPerfil()">
                    <option selected="selected" value="">Seleccione un perfil...</option>
                </select>
                <span asp-validation-for="Perfil" class="text-danger"></span>
            </div>
            <div class="form-group" id="grupo_plan">
                <label asp-for="Plan" class="control-label"></label>
                <select asp-for="Plan" class="form-control" asp-items="Html.GetEnumSelectList<Plan>()">
                    <option selected="selected" value="">Seleccione un plan...</option>
                </select>
                <span asp-validation-for="Plan" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Crear" class="btn btn-primary" />
                <a asp-action="Index" class="btn btn-default">Cancelar</a>
            </div>
        </form>
    </div>
</div>


@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
    <script>$(document).ready(listenerPerfil());</script>
}

ProyectoGym/Views/Usuario/Delete.cshtml
@model ProyectoGym.Models.Usuario

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Borrar</h1>

<h3>Esta seguro que quiere borrar el usuario?</h3>
<div>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Nombres)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nombres)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Apellidos)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Apellidos)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.NombreUsuario)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.NombreUsuario)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Perfil)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Perfil)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Plan)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Plan)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Borrar" class="btn btn-danger" /> 
        <a asp-action="Index" class="btn btn-default">Cancelar</a>
    </form>
</div>

ProyectoGym/Views/Usuario/Details.cshtml
@model ProyectoGym.Models.Usuario

@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Detalles</h1>

<div>
    <h4>Usuario</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Nombres)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nombres)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Apellidos)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Apellidos)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.NombreUsuario)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.NombreUsuario)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Perfil)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Perfil)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Plan)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Plan)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Editar</a> |
    <a asp-action="Index">Volver</a>
</div>

ProyectoGym/Views/Usuario/Edit.cshtml
@model ProyectoGym.Models.Usuario

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Editar</h1>

<h4>Usuario</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit"  onsubmit="return validateFormUser()">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Nombres" class="control-label"></label>
                <input asp-for="Nombres" class="form-control" />
                <span asp-validation-for="Nombres" class="text-danger"></span>
            </div>
                <input type="hidden" asp-for="Password" class="form-control" />
            <div class="form-group">
                <label asp-for="Apellidos" class="control-label"></label>
                <input asp-for="Apellidos" class="form-control" />
                <span asp-validation-for="Apellidos" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="NombreUsuario" class="control-label"></label>
                <input asp-for="NombreUsuario" class="form-control" />
                <span asp-validation-for="NombreUsuario" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Perfil" class="control-label"></label>
                <select asp-for="Perfil" class="form-control" asp-items="Html.GetEnumSelectList<Perfil>()" onchange="listenerPerfil()">
                    <option selected="selected" value="">Seleccione un perfil...</option>
                </select>
                <span asp-validation-for="Perfil" class="text-danger"></span>
            </div>
            <div class="form-group" id="grupo_plan">
                <label asp-for="Plan" class="control-label"></label>
                <select asp-for="Plan" class="form-control" asp-items="Html.GetEnumSelectList<Plan>()">
                    <option selected="selected" value="">Seleccione un plan...</option>
                </select>
                <span asp-validation-for="Plan" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Guardar" class="btn btn-primary" />
                <a asp-action="Index" class="btn btn-default">Cancelar</a>
            </div>
        </form>
    </div>
</div>



@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
    <script>$(document).ready(listenerPerfil());</script>
}

ProyectoGym/Views/Usuario/Index.cshtml
@model IEnumerable<ProyectoGym.Models.Usuario>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1 class="text-center">Usuario</h1>

<div class = "row">
    <div class="col-md-12">
        <p>
            <a asp-action="Create" class= "btn btn-primary float-right">Agregar usuario</a>
        </p>
    </div>   
</div>

<div class="row">
    <div class="col-md-12">
        <table class="table table-hover mt-4">
            <thead>
                <tr>
                    <th>
                        @Html.DisplayNameFor(model => model.Nombres)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Apellidos)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.NombreUsuario)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Perfil)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Plan)
                    </th>
                    <th></th>

                </tr>
            </thead>

            <tbody>
        @foreach (var item in Model) {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Nombres)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Apellidos)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.NombreUsuario)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Perfil)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Plan)
                    </td>
                    <td>
                        <div class="btn-group float-right">
                            <a asp-action="Edit" asp-route-id="@item.Id"class="btn btn-outline-primary btn-sm">Editar</a> 
                            <a asp-action="Delete" asp-route-id="@item.Id"class="btn btn-outline-danger btn-sm">Borrar</a> 
                            <a asp-area="" asp-controller="ActividadesUsuarios" asp-route-id="@item.Id" asp-action="Index" class="btn btn-outline-info btn-sm">Actividades</a> 
                            <a asp-area="" asp-controller="Rutina" asp-route-userId="@item.Id" asp-action="Index"class="btn btn-outline-info btn-sm">Rutinas</a>
                        </div>
                    </td>
                </tr>
        }
            </tbody>

        </table>
    </div> 
</div> 